/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/New/Pages_016.glb --types 
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane_016: THREE.Mesh;
    Plane_016_1: THREE.Mesh;
    Plane_017: THREE.Mesh;
    Plane_017_1: THREE.Mesh;
    Plane_023: THREE.Mesh;
    Plane_023_1: THREE.Mesh;
    Plane_022: THREE.Mesh;
    Plane_022_1: THREE.Mesh;
    Plane_020: THREE.Mesh;
    Plane_020_1: THREE.Mesh;
    Plane_018: THREE.Mesh;
    Plane_018_1: THREE.Mesh;
    Plane_019: THREE.Mesh;
    Plane_019_1: THREE.Mesh;
    Plane_021: THREE.Mesh;
    Plane_021_1: THREE.Mesh;
  };
  materials: {
    ["Opaline Paper"]: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "Key.016Action"
  | "Key.017Action"
  | "Key.023Action"
  | "Key.022Action"
  | "Key.020Action"
  | "Key.018Action"
  | "Key.019Action"
  | "Key.021Action";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}
type propsBook = JSX.IntrinsicElements["group"] & {
  DiffuseMap: THREE.Texture;
  BumpMap: THREE.Texture;
  StartAnimation: Boolean;
  ImagesReady: Boolean;
  Textures: THREE.Texture[];
};

export function Pages_016(props: propsBook) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/Models/New/Pages_016.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  const nd = Object.entries(nodes);
  const nodesArray = nd.filter((item) => {
    if (item[0].startsWith("Plane") && !item[0].endsWith("_1")) {
      return true;
    }
    return false;
  });
  materials["Opaline Paper"].color = new THREE.Color("white");
  materials["Opaline Paper"].map = props.DiffuseMap;
  materials["Opaline Paper"].map.flipY = false;
  materials["Opaline Paper"].needsUpdate = true;
  const materialsArray = new Array(8).fill(materials["Opaline Paper"]);
  const [Materials, setMaterials] =
    useState<THREE.MeshStandardMaterial[]>(materialsArray); // Assuming image exists by default

  useEffect(() => {
    if (props.ImagesReady && props.Textures) {
      const Pages = props.Textures;
      const mt: THREE.MeshStandardMaterial[] = [];
      Materials.map((material, index) => {
        const mat = material.clone();
        mat.map = Pages[index];
        mat.needsUpdate = true;
        mt.push(mat);
      });
      setMaterials(mt);
    } else {
      setMaterials(materialsArray);
    }
  }, [props.ImagesReady]);
  useEffect(() => {
    if (props.StartAnimation) {
      Object.entries(actions).map(([key, value]) => {
        value?.setLoop(THREE.LoopOnce, 0);
        value?.play().reset();
      });
    }
  }, [props.StartAnimation]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        {Materials.map((material, index) => {
          return (
            <mesh
              key={index}
              castShadow
              name={nodesArray[index][0]}
              geometry={nodesArray[index][1].geometry}
              material={material}
              morphTargetDictionary={nodesArray[index][1].morphTargetDictionary}
              morphTargetInfluences={nodesArray[index][1].morphTargetInfluences}
            />
          );
        })}
        <mesh
          name="Plane_016_1"
          geometry={nodes.Plane_016_1.geometry}
          material={materials.White}
          morphTargetDictionary={nodes.Plane_016_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane_016_1.morphTargetInfluences}
        />
        <mesh
          name="Plane_017_1"
          geometry={nodes.Plane_017_1.geometry}
          material={materials.White}
          morphTargetDictionary={nodes.Plane_017_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane_017_1.morphTargetInfluences}
        />
        <mesh
          name="Plane_023_1"
          geometry={nodes.Plane_023_1.geometry}
          material={materials.White}
          morphTargetDictionary={nodes.Plane_023_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane_023_1.morphTargetInfluences}
        />
        <mesh
          name="Plane_022_1"
          geometry={nodes.Plane_022_1.geometry}
          material={materials.White}
          morphTargetDictionary={nodes.Plane_022_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane_022_1.morphTargetInfluences}
        />
        <mesh
          name="Plane_020_1"
          geometry={nodes.Plane_020_1.geometry}
          material={materials.White}
          morphTargetDictionary={nodes.Plane_020_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane_020_1.morphTargetInfluences}
        />
        <mesh
          name="Plane_018_1"
          geometry={nodes.Plane_018_1.geometry}
          material={materials.White}
          morphTargetDictionary={nodes.Plane_018_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane_018_1.morphTargetInfluences}
        />
        <mesh
          name="Plane_019_1"
          geometry={nodes.Plane_019_1.geometry}
          material={materials.White}
          morphTargetDictionary={nodes.Plane_019_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane_019_1.morphTargetInfluences}
        />
        <mesh
          name="Plane_021_1"
          geometry={nodes.Plane_021_1.geometry}
          material={materials.White}
          morphTargetDictionary={nodes.Plane_021_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane_021_1.morphTargetInfluences}
        />
      </group>
    </group>
  );
}
useGLTF.preload("/Models/New/Pages_016.glb");
