/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Pages_032.glb --types --transform 
Files: Pages_032.glb [44.86MB] > C:\Users\Origin Systems\Desktop\Job\MyWork\work\3D BookFlip\bookflip\public\Models\Pages_032-transformed.glb [43.31MB] (3%)
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { GetTextures } from "./Pages_000";

type GLTFResult = GLTF & {
  nodes: {
    Pages_032: THREE.Mesh;
    Pages_033: THREE.Mesh;
    Pages_034: THREE.Mesh;
    Pages_035: THREE.Mesh;
    Pages_036: THREE.Mesh;
    Pages_037: THREE.Mesh;
    Pages_038: THREE.Mesh;
    Pages_039: THREE.Mesh;
  };
  materials: {
    ["Opaline Paper"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "Key.036Action"
  | "Key.037Action"
  | "Key.038Action"
  | "Key.039Action"
  | "Key.040Action"
  | "Key.041Action"
  | "Key.042Action"
  | "Key.043Action";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}
type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;
type propsBook = JSX.IntrinsicElements["group"] & {
  DiffuseMap: THREE.Texture;
  BumpMap: THREE.Texture;
  StartAnimation: Boolean;
  ImagesReady: Boolean;
  Textures: THREE.Texture[];
};
export function Pages_032(props: propsBook) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/Models/Transformed/Pages_032.glb"
  ) as GLTFResult;
  const nodesArray = Object.entries(nodes);
  materials["Opaline Paper"].needsUpdate = true;
  materials["Opaline Paper"].map = props.DiffuseMap;
  const materialsArray = new Array(8).fill(materials["Opaline Paper"]);
  const [Materials, setMaterials] =
    useState<THREE.MeshStandardMaterial[]>(materialsArray); // Assuming image exists by default

  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (props.ImagesReady) {
      const Pages = props.Textures;
      const mt: THREE.MeshStandardMaterial[] = [];
      Materials.map((material, index) => {
        const mat = material.clone();
        mat.map = Pages[index];
        mat.needsUpdate = true;
        mt.push(mat);
      });
      setMaterials(mt);
    } else {
      setMaterials(materialsArray);
    }
  }, [props.ImagesReady]);
  useEffect(() => {
    if (props.StartAnimation)
      Object.entries(actions).map(([key, value]) => {
        value?.setLoop(THREE.LoopOnce, 0);
        value?.play().reset();
      });
  }, [props.StartAnimation]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        {Materials.map((material, index) => {
          return (
            <mesh
              key={index}
              castShadow
              name={nodesArray[index + 1][0]}
              geometry={nodesArray[index + 1][1].geometry}
              material={material}
              morphTargetDictionary={
                nodesArray[index + 1][1].morphTargetDictionary
              }
              morphTargetInfluences={
                nodesArray[index + 1][1].morphTargetInfluences
              }
            />
          );
        })}
        {/* <mesh
          castShadow
          name="Pages_032"
          geometry={nodes.Pages_032.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_032.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_032.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_033"
          geometry={nodes.Pages_033.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_033.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_033.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_034"
          geometry={nodes.Pages_034.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_034.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_034.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_035"
          geometry={nodes.Pages_035.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_035.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_035.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_036"
          geometry={nodes.Pages_036.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_036.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_036.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_037"
          geometry={nodes.Pages_037.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_036.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_036.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_038"
          geometry={nodes.Pages_038.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_038.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_038.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_039"
          geometry={nodes.Pages_039.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_039.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_039.morphTargetInfluences}
        /> */}
      </group>
    </group>
  );
}

//useGLTF.preload("/Models/Transformed/Pages_032.glb");
