/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Pages_008.glb --types --transform 
Files: Pages_008.glb [45.01MB] > C:\Users\Origin Systems\Desktop\Job\MyWork\work\3D BookFlip\bookflip\public\Models\Pages_008-transformed.glb [43.46MB] (3%)
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { GetTextures } from "./Pages_000";

type GLTFResult = GLTF & {
  nodes: {
    Pages_008: THREE.Mesh;
    Pages_009: THREE.Mesh;
    Pages_010: THREE.Mesh;
    Pages_011: THREE.Mesh;
    Pages_012: THREE.Mesh;
    Pages_013: THREE.Mesh;
    Pages_014: THREE.Mesh;
    Pages_015: THREE.Mesh;
  };
  materials: {
    ["Opaline Paper"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "Key.012Action"
  | "Key.013Action"
  | "Key.014Action"
  | "Key.015Action"
  | "Key.016Action"
  | "Key.017Action"
  | "Key.018Action"
  | "Key.019Action";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}
type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;
type propsBook = JSX.IntrinsicElements["group"] & {
  DiffuseMap: THREE.Texture;
  BumpMap: THREE.Texture;
  StartAnimation: Boolean;
  ImagesReady: Boolean;
  Textures: THREE.Texture[];
};
export function Pages_008(props: propsBook) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/Models/Transformed/Pages_008.glb"
  ) as GLTFResult;

  const nodesArray = Object.entries(nodes);
  materials["Opaline Paper"].needsUpdate = true;
  materials["Opaline Paper"].map = props.DiffuseMap;
  const materialsArray = new Array(8).fill(materials["Opaline Paper"]);
  const [Materials, setMaterials] =
    useState<THREE.MeshStandardMaterial[]>(materialsArray); // Assuming image exists by default

  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (props.ImagesReady) {
      const Pages = props.Textures;
      const mt: THREE.MeshStandardMaterial[] = [];
      Materials.map((material, index) => {
        const mat = material.clone();
        mat.map = Pages[index];
        mat.needsUpdate = true;
        mt.push(mat);
      });
      setMaterials(mt);
    } else {
      setMaterials(materialsArray);
    }
  }, [props.ImagesReady]);

  useEffect(() => {
    if (props.StartAnimation)
      Object.entries(actions).map(([key, value]) => {
        value?.setLoop(THREE.LoopOnce, 0);
        value?.play().reset();
      });
  }, [props.StartAnimation]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        {Materials.map((material, index) => {
          return (
            <mesh
              key={index}
              castShadow
              name={nodesArray[index + 1][0]}
              geometry={nodesArray[index + 1][1].geometry}
              material={material}
              morphTargetDictionary={
                nodesArray[index + 1][1].morphTargetDictionary
              }
              morphTargetInfluences={
                nodesArray[index + 1][1].morphTargetInfluences
              }
            />
          );
        })}
        {/* <mesh
          castShadow
          name="Pages_008"
          geometry={nodes.Pages_008.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_008.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_008.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_009"
          geometry={nodes.Pages_009.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_009.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_009.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_010"
          geometry={nodes.Pages_010.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_010.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_010.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_011"
          geometry={nodes.Pages_011.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_011.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_011.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_012"
          geometry={nodes.Pages_012.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_012.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_012.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_013"
          geometry={nodes.Pages_013.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_013.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_013.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_014"
          geometry={nodes.Pages_014.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_014.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_014.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_015"
          geometry={nodes.Pages_015.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_015.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_015.morphTargetInfluences}
        /> */}
      </group>
    </group>
  );
}

//useGLTF.preload("/Models/Transformed/Pages_008.glb");
