/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Pages_024.glb --types --transform 
Files: Pages_024.glb [45.12MB] > C:\Users\Origin Systems\Desktop\Job\MyWork\work\3D BookFlip\bookflip\public\Models\Pages_024-transformed.glb [43.57MB] (3%)
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { GetTextures } from "./Pages_000";

type GLTFResult = GLTF & {
  nodes: {
    Pages_024: THREE.Mesh;
    Pages_025: THREE.Mesh;
    Pages_026: THREE.Mesh;
    Pages_027: THREE.Mesh;
    Pages_028: THREE.Mesh;
    Pages_029: THREE.Mesh;
    Pages_030: THREE.Mesh;
    Pages_031: THREE.Mesh;
  };
  materials: {
    ["Opaline Paper"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "Key.028Action"
  | "Key.029Action"
  | "Key.030Action"
  | "Key.031Action"
  | "Key.032Action"
  | "Key.033Action"
  | "Key.034Action"
  | "Key.035Action";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}
type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;
type propsBook = JSX.IntrinsicElements["group"] & {
  DiffuseMap: THREE.Texture;
  BumpMap: THREE.Texture;
  StartAnimation: Boolean;
  ImagesReady: Boolean;
};
export function Pages_024(props: propsBook) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/Models/Transformed/Pages_024.glb"
  ) as GLTFResult;
  const nodesArray = Object.entries(nodes);
  materials["Opaline Paper"].needsUpdate = true;
  materials["Opaline Paper"].map = props.DiffuseMap;
  const materialsArray = new Array(8).fill(materials["Opaline Paper"]);
  const [Materials, setMaterials] =
    useState<THREE.MeshStandardMaterial[]>(materialsArray); // Assuming image exists by default

  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (props.ImagesReady) {
      const Pages = GetTextures(nodesArray, 24);
      const mt: THREE.MeshStandardMaterial[] = [];
      Materials.map((material, index) => {
        const mat = material.clone();
        mat.map = Pages[index];
        mat.needsUpdate = true;
        mt.push(mat);
      });
      setMaterials(mt);
    } else {
      setMaterials(materialsArray);
    }
  }, [props.ImagesReady]);

  useEffect(() => {
    if (props.StartAnimation)
      Object.entries(actions).map(([key, value]) => {
        value?.setLoop(THREE.LoopOnce, 0);
        value?.play().reset();
      });
  }, [props.StartAnimation]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        {Materials.map((material, index) => {
          return (
            <mesh
              key={index}
              castShadow
              name={nodesArray[index + 1][0]}
              geometry={nodesArray[index + 1][1].geometry}
              material={material}
              morphTargetDictionary={
                nodesArray[index + 1][1].morphTargetDictionary
              }
              morphTargetInfluences={
                nodesArray[index + 1][1].morphTargetInfluences
              }
            />
          );
        })}
        {/* <mesh
          castShadow
          name="Pages_024"
          geometry={nodes.Pages_024.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_024.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_024.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_025"
          geometry={nodes.Pages_025.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_025.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_025.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_026"
          geometry={nodes.Pages_026.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_026.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_026.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_027"
          geometry={nodes.Pages_027.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_027.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_027.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_028"
          geometry={nodes.Pages_028.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_028.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_028.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_029"
          geometry={nodes.Pages_029.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_029.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_029.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_030"
          geometry={nodes.Pages_030.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_030.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_030.morphTargetInfluences}
        />
        <mesh
          castShadow
          name="Pages_031"
          geometry={nodes.Pages_031.geometry}
          material={materials["Opaline Paper"]}
          morphTargetDictionary={nodes.Pages_031.morphTargetDictionary}
          morphTargetInfluences={nodes.Pages_031.morphTargetInfluences}
        /> */}
      </group>
    </group>
  );
}

//useGLTF.preload("/Models/Transformed/Pages_024.glb");
